[project]
name = "minedelta"
version = "0.1.0"
requires-python = ">=3.11"
description = "(UNOFFICIAL) Minecraft Server Backup System"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["Minecraft", "Minecraft server", "differential backup", "backup", "versioning"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",

    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: System Administrators",

    "Operating System :: OS Independent",

    "Topic :: System :: Archiving :: Backup",
    "Topic :: Games/Entertainment",
    "Topic :: Utilities",

    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",

    "Typing :: Typed",
]

dependencies = [
    "msgspec>=0.20.0",
]

[project.urls]
Source = "https://github.com/Birnendampf/MineDelta"

[project.optional-dependencies]
git = [
    "dulwich>=1.0.0",
]
lz4 = [
    "lz4>=4.4.5",
]

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "ruff>=0.14.14",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["UP"]


[tool.mypy]
strict = true
packages = "minedelta"
