[project]
name = "mineback"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "msgspec>=0.20.0",
]

[project.optional-dependencies]
git = [
    "dulwich>=1.0.0",
]
lz4 = [
    "lz4>=4.4.5",
]

[build-system]
requires = ["uv_build>=0.9.9,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "ruff>=0.14.14",
]

[tool.ruff]
line-length = 100


[tool.mypy]
strict = true
packages = "mineback"
